import { createElement, useEffect, type ComponentType } from 'react';
import { AppRegistry } from 'react-native';

import { buildXrMode, ensureEyeTrackingPermission } from './eyeTrackingPermission';

/**
 * Root component name PICO's immersive activity mounts.
 *
 * `withPicoLauncherActivity` puts the PICO VR intent categories onto
 * `.VRActivity`, and that activity — generated by the renderer's own config
 * plugin — mounts a React root under this name.
 */
export const IMMERSIVE_ROOT_COMPONENT = 'VRQuestScene';

/**
 * Register the component the immersive activity mounts.
 *
 * Call this at module scope from the app entry, before any navigation:
 * `enterImmersiveScene()` starts the activity immediately, and a component
 * registered later — from a lazily-loaded route, say — arrives after the
 * activity has already looked for it and found nothing, which shows as an
 * immersive view stuck on a blank loading screen.
 *
 * ```js
 * // index.js
 * import 'expo-router/entry';
 * import { registerImmersiveScene } from '@expo-pico/core';
 * import { MyVrScene } from './src/scene/MyVrScene';
 *
 * registerImmersiveScene(MyVrScene);
 * ```
 *
 * For a custom immersive root only. The PICO-aware mikevocalz/viro fork
 * registers its own ViroQuestEntryPoint and sets its intent on both Quest and
 * PICO. Apps using ViroXRSceneNavigator should keep that registration: replacing
 * it bypasses the scene intent, navigation proxy, view tag, and exit callbacks.
 * Older upstream Viro builds without a PICO launch path may still use this
 * helper with their own renderer integration.
 */
export function registerImmersiveScene(component: ComponentType<object>): void {
  const root = withImmersiveEyeTracking(component);
  AppRegistry.registerComponent(IMMERSIVE_ROOT_COMPONENT, () => root);
}

/**
 * Wraps the scene so the eye tracking request happens on mount, inside the
 * immersive activity. Meta: "Hybrid apps that need eye tracking in immersive
 * mode must declare the permission but only request it at runtime when the
 * immersive activity launches." The 2D panel never asks.
 *
 * Fire-and-forget: the scene renders right away, and a denial leaves
 * selection on the hand ray. The once-per-process guard in
 * `ensureEyeTrackingPermission` keeps re-entries from prompting again.
 */
function withImmersiveEyeTracking(Scene: ComponentType<object>): ComponentType<object> {
  function ImmersiveSceneRoot(props: object) {
    useEffect(() => {
      // Never rejects; nothing to await.
      ensureEyeTrackingPermission(buildXrMode()).catch(() => undefined);
    }, []);
    return createElement(Scene, props);
  }
  ImmersiveSceneRoot.displayName = `ImmersiveSceneRoot(${
    Scene.displayName ?? Scene.name ?? 'Scene'
  })`;
  return ImmersiveSceneRoot;
}

/**
 * Whether a root component is registered for the immersive activity.
 *
 * Used to fail loudly instead of silently: an unregistered root shows up as an
 * immersive view stuck on a blank loading screen, with nothing in logcat and no
 * error anywhere, which is a miserable thing to debug from the inside of a
 * headset.
 */
export function hasImmersiveSceneRegistered(): boolean {
  return AppRegistry.getAppKeys().includes(IMMERSIVE_ROOT_COMPONENT);
}
