import type { ComponentType } from 'react';
import { AppRegistry } from 'react-native';

/**
 * Root component name PICO's immersive activity mounts.
 *
 * `withPicoLauncherActivity` puts the PICO VR intent categories onto
 * `.VRActivity`, and that activity — generated by the renderer's own config
 * plugin — mounts a React root under this name.
 */
export const IMMERSIVE_ROOT_COMPONENT = 'VRQuestScene';

/**
 * Register the component the immersive activity mounts.
 *
 * Call this at module scope from the app entry, before any navigation:
 * `enterImmersiveScene()` starts the activity immediately, and a component
 * registered later — from a lazily-loaded route, say — arrives after the
 * activity has already looked for it and found nothing, which shows as an
 * immersive view stuck on a blank loading screen.
 *
 * ```js
 * // index.js
 * import 'expo-router/entry';
 * import { registerImmersiveScene } from '@expo-pico/core';
 * import { MyVrScene } from './src/scene/MyVrScene';
 *
 * registerImmersiveScene(MyVrScene);
 * ```
 *
 * This deliberately overrides `@reactvision/react-viro`, which auto-registers
 * its own `ViroQuestEntryPoint` under the same name on import. That component
 * renders whatever `VRQuestNavigatorBridge.getIntent()` returns, and the intent
 * is only ever set on Viro's Quest-gated path — `ViroPlatform.isQuest` matches
 * `Build.MANUFACTURER`/`BRAND` against Oculus and Meta, so it is false on PICO
 * and no intent is ever set. Viro's own entry point documents this override as
 * supported.
 */
export function registerImmersiveScene(component: ComponentType<object>): void {
  AppRegistry.registerComponent(IMMERSIVE_ROOT_COMPONENT, () => component);
}

/**
 * Whether a root component is registered for the immersive activity.
 *
 * Used to fail loudly instead of silently: an unregistered root shows up as an
 * immersive view stuck on a blank loading screen, with nothing in logcat and no
 * error anywhere, which is a miserable thing to debug from the inside of a
 * headset.
 */
export function hasImmersiveSceneRegistered(): boolean {
  return AppRegistry.getAppKeys().includes(IMMERSIVE_ROOT_COMPONENT);
}
