import {
  ConfigPlugin,
  withAndroidManifest,
  withDangerousMod,
  AndroidConfig,
} from '@expo/config-plugins';
import * as fs from 'fs';
import * as path from 'path';

import {
  MANIFEST_META,
  PICO_FEATURES,
  DEVICE_TARGET_MAP,
  TARGET_PROFILE_MAP,
  PICO_PROHIBITED_PERMISSIONS,
  XR_MODE_MANIFEST_VALUE,
} from './constants';
import type { ResolvedPicoOptions } from './types';
import { resolveTargetProfile } from './types';
import { applyCapabilityContract } from './withPicoCapabilities';
import {
  applyPicoFlavorEntries,
  getPicoFlavorManifestState,
  resolvePicoManifestRoute,
  withPicoFlavorMetaData,
  withPicoMobileFlavorManifest,
} from './withPicoFlavorEntries';
import { applyLauncherContract } from './withPicoLauncherActivity';
import { applyVRActivityContract, applyPanelSize } from './withPicoVRActivity';
import { applyPlatformServiceContract } from './withPicoPlatformService';

/**
 * Declares `pvr.app.id`, the only PICO Platform Service meta-data core emits.
 * The PPS SDK reads it via `AppUtils.getAppIdFromManifest("pvr.app.id")` and
 * rejects calls with 100008 "appkey is empty" when the APK lacks it.
 *
 * Routing (see `PicoManifestRoute`): with a pico flavor it goes to the pico,
 * dual and mobile flavor manifests; with no pico flavor but a quest flavor
 * (expo-horizon-core next to `buildVariant: 'mobile'`) it goes to the mobile
 * flavor; a single-variant app gets it in main. The quest flavor targets Meta
 * Horizon, which has no PPS, so it never gets it, and a copy an older
 * prebuild left in main or in the mobile flavor is removed when it no longer
 * belongs there.
 *
 * Gated on the same ID withPicoStrings writes to `@string/pico_app_id`
 * (`platformService.picoAppId`, falling back to `picoAppId`), so the
 * reference never dangles.
 */
export const withPicoPlatformServiceManifest: ConfigPlugin<ResolvedPicoOptions> = (
  config,
  options
) => {
  // Registered even with no ID, so stale copies in the mobile flavor are cleaned.
  config = withPicoMobileFlavorManifest(config);
  const appId = options.platformService.picoAppId ?? options.picoAppId;
  if (!appId) {
    // Nothing to declare, but drop a copy an older prebuild left in main
    // unless main is where it belongs.
    return withAndroidManifest(config, (cfg) => {
      const application = cfg.modResults.manifest.application?.[0];
      if (resolvePicoManifestRoute(cfg) !== 'main' && application?.['meta-data']) {
        application['meta-data'] = application['meta-data'].filter(
          (m) => m.$?.['android:name'] !== MANIFEST_META.PICO_APP_ID
        );
      }
      return cfg;
    });
  }
  return withPicoFlavorMetaData(config, {
    name: MANIFEST_META.PICO_APP_ID,
    value: '@string/pico_app_id',
    mobileFlavor: true,
  });
};

function detectExpoDevClient(projectRoot: string): boolean {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(projectRoot, 'package.json'), 'utf8'));
    return Boolean(
      pkg.dependencies?.['expo-dev-client'] || pkg.devDependencies?.['expo-dev-client']
    );
  } catch {
    return false;
  }
}

export const withPicoAndroidManifest: ConfigPlugin<ResolvedPicoOptions> = (config, options) => {
  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const picoManifestDir = path.join(projectRoot, 'android', 'app', 'src', 'pico');
      const picoManifestPath = path.join(picoManifestDir, 'AndroidManifest.xml');

      if (!fs.existsSync(picoManifestDir)) {
        fs.mkdirSync(picoManifestDir, { recursive: true });
      }

      // Detect expo-dev-client so we skip the IMMERSIVE_HMD launcher
      // intent-filter on MainActivity — its 2D RN/dev-launcher root can't
      // fulfill the immersive HMD surface and PICO black-screens. Keep
      // pvr.app.type/spatialMode honored so MR builds still get the
      // passthrough capability at app level; only the launcher contract
      // changes. Viro's VRActivity owns immersive entry either way.
      const hasDevClient = detectExpoDevClient(projectRoot);
      const manifest = buildPicoManifest(options);
      // Launcher contract: pvr.app.type meta + immersive launcher
      // categories on .MainActivity + <queries> for PICO system packages.
      // Mutates the manifest object in place; gated on resolved appType.
      applyLauncherContract(manifest, options, { hasDevClient });
      // VRActivity contract: adds PICO intent-filter categories + spatial
      // immersive meta-data to the .VRActivity generated by the
      // @reactvision/react-viro plugin. Required so PICO routes the
      // immersive HMD surface to VRActivity (not MainActivity, which stays
      // a 2D panel / window-container).
      applyVRActivityContract(manifest, options);
      // Panel size contract: emits <layout android:defaultWidth/Height>
      // on .MainActivity when the user specified the Horizon-parity panel
      // dimensions. No-op when both options are unset.
      applyPanelSize(manifest, options);
      // Platform SDK contract: UnityAuthInterface + PicoSDKBrowser
      // activities. Gated on platformService.hasIdentity && declareActivities.
      applyPlatformServiceContract(manifest, options);
      // Hardware capabilities: eye/face/body tracking features +
      // permissions, spatial-audio + foveation features, refresh-rate
      // meta-data. Each capability is independently gated; all writes
      // are idempotent and toggling off cleans up the entry.
      applyCapabilityContract(manifest, options);
      // PICO-only permissions/features recorded by feature plugins through
      // withPicoFlavorPermission / withPicoFlavorFeature.
      applyPicoFlavorEntries(manifest, getPicoFlavorManifestState(config));
      await AndroidConfig.Manifest.writeAndroidManifestAsync(picoManifestPath, manifest);
      console.log(`✅ Created PICO-specific AndroidManifest at: ${picoManifestPath}`);

      // If dual variant, also write a dual/ source set manifest
      if (options.buildVariant === 'dual') {
        const dualDir = path.join(projectRoot, 'android', 'app', 'src', 'dual');
        if (!fs.existsSync(dualDir)) fs.mkdirSync(dualDir, { recursive: true });
        const dualManifestPath = path.join(dualDir, 'AndroidManifest.xml');
        await AndroidConfig.Manifest.writeAndroidManifestAsync(dualManifestPath, manifest);
        console.log(`✅ Created dual-variant AndroidManifest at: ${dualManifestPath}`);
      }

      return config;
    },
  ]);

  return config;
};

function buildPicoManifest(options: ResolvedPicoOptions): AndroidConfig.Manifest.AndroidManifest {
  const effectiveProfile = resolveTargetProfile(options);

  const manifest: AndroidConfig.Manifest.AndroidManifest = {
    manifest: {
      $: {
        'xmlns:android': 'http://schemas.android.com/apk/res/android',
        'xmlns:tools': 'http://schemas.android.com/tools',
      },
      queries: [],
      'uses-permission': [],
      'uses-feature': [],
      application: [],
    },
  };

  for (const permission of PICO_PROHIBITED_PERMISSIONS) {
    const fullName = permission.includes('.') ? permission : `android.permission.${permission}`;
    manifest.manifest['uses-permission']!.push({
      $: { 'android:name': fullName, 'tools:node': 'remove' },
    } as any);
  }
  console.log(
    `🚫 Blocked ${PICO_PROHIBITED_PERMISSIONS.length} prohibited permissions in PICO manifest`
  );

  // VR headtracking — required false when emulator optimizations on
  const headtrackingRequired = options.enableEmulatorOptimizations ? 'false' : 'true';
  manifest.manifest['uses-feature']!.push({
    $: {
      'android:name': PICO_FEATURES.VR_HEADTRACKING,
      'android:required': headtrackingRequired,
      'android:version': '1',
    },
  } as any);

  if (options.handTracking) {
    manifest.manifest['uses-feature']!.push({
      $: { 'android:name': PICO_FEATURES.HAND_TRACKING, 'android:required': 'false' },
    } as any);
  }

  if (options.passthrough) {
    manifest.manifest['uses-feature']!.push({
      $: { 'android:name': PICO_FEATURES.PASSTHROUGH, 'android:required': 'false' },
    } as any);
  }

  if (options.sceneUnderstanding) {
    manifest.manifest['uses-feature']!.push({
      $: { 'android:name': PICO_FEATURES.SCENE_UNDERSTANDING, 'android:required': 'false' },
    } as any);
  }

  // Swan target gets spatial anchor feature declaration
  if (effectiveProfile === 'swan') {
    manifest.manifest['uses-feature']!.push({
      $: { 'android:name': PICO_FEATURES.SPATIAL_ANCHOR, 'android:required': 'false' },
    } as any);
  }

  const application: any = {
    $: {
      'android:allowBackup': 'false',
      'tools:replace': 'android:allowBackup',
    },
    'meta-data': [],
    activity: [],
  };

  // pvr.app.id is recorded by withPicoPlatformServiceManifest and added
  // with the other recorded entries by applyPicoFlavorEntries.

  if (options.targetDevices.length > 0) {
    const deviceValues = options.targetDevices.map((d) => DEVICE_TARGET_MAP[d] ?? d).join('|');
    application['meta-data'].push({
      $: { 'android:name': MANIFEST_META.SUPPORTED_DEVICES, 'android:value': deviceValues },
    });
  }

  if (options.spatialMode !== '2d') {
    application['meta-data'].push({
      $: { 'android:name': MANIFEST_META.SPATIAL_MODE, 'android:value': options.spatialMode },
    });
  }

  if (options.defaultContainerMode !== 'none') {
    application['meta-data'].push({
      $: {
        'android:name': MANIFEST_META.CONTAINER_MODE,
        'android:value': options.defaultContainerMode,
      },
    });
  }

  // Always write target profile (resolved)
  application['meta-data'].push({
    $: {
      'android:name': MANIFEST_META.TARGET_PROFILE,
      'android:value': TARGET_PROFILE_MAP[effectiveProfile] ?? effectiveProfile,
    },
  });

  // Always write xrMode so PICO OS launchers / entitlement checks can read it
  // without instantiating the app. Mirrors BuildConfig.PICO_XR_MODE.
  application['meta-data'].push({
    $: {
      'android:name': MANIFEST_META.XR_MODE,
      'android:value': XR_MODE_MANIFEST_VALUE[options.xrMode] ?? options.xrMode,
    },
  });

  if (options.xrMode === 'pico-swan') {
    if (options.picoSwan.declareSpatialContainerCategory) {
      application['meta-data'].push({
        $: {
          'android:name': MANIFEST_META.SWAN_SPATIAL_CONTAINER,
          'android:value':
            options.defaultContainerMode === 'none'
              ? 'window-container'
              : options.defaultContainerMode,
        },
      });
    }
    if (options.picoSwan.swanSdkArtifact) {
      // Encode the artifact version into the manifest as a debug aid
      // (PICO support tooling typically inspects manifest meta to know
      // which Swan runtime an APK was built against).
      const versionFragment = options.picoSwan.swanSdkArtifact.split(':').pop() ?? '';
      if (versionFragment) {
        application['meta-data'].push({
          $: {
            'android:name': MANIFEST_META.SWAN_RUNTIME_VERSION,
            'android:value': versionFragment,
          },
        });
      }
    }
  }

  if (options.entitlementCheck) {
    application['meta-data'].push({
      $: { 'android:name': MANIFEST_META.ENTITLEMENT_CHECK, 'android:value': 'true' },
    });
  }

  if (options.developerTools) {
    application['meta-data'].push({
      $: { 'android:name': MANIFEST_META.DEVELOPER_TOOLS, 'android:value': 'true' },
    });
  }

  manifest.manifest.application!.push(application);
  return manifest;
}

export default withPicoAndroidManifest;
