#!/usr/bin/env bash
# Removes the Expo Modules files left behind by the Nitro conversion.
# Dry run by default; pass --apply to delete.
# Add --with-example to also drop the files the example redesign superseded.
set -euo pipefail

cd "$(dirname "$0")/.."

APPLY=0
[[ "${1:-}" == "--apply" ]] && APPLY=1

PACKAGES=(
  account achievements iap leaderboards notifications
  rooms rtc social spatial storage subscription
)

targets=()

# Per-package Expo native module wrappers, replaced by *.nitro.ts specs.
for p in "${PACKAGES[@]}"; do
  for f in packages/expo-pico-"$p"/src/ExpoPico*Module.ts; do
    [[ -e "$f" ]] && targets+=("$f")
  done
  # Expo autolinking manifest, replaced by nitro.json.
  f="packages/expo-pico-$p/expo-module.config.json"
  [[ -e "$f" ]] && targets+=("$f")
  # Hand-written types superseded by the *.nitro.ts spec. Skipped where the
  # package's index.ts still imports './types' — spatial keeps its own, since
  # its public API exposes typed arrays the spec deliberately does not model.
  f="packages/expo-pico-$p/src/types.ts"
  if [[ -e "$f" ]] && ! grep -q "from './types'" "packages/expo-pico-$p/src/index.ts" 2>/dev/null; then
    targets+=("$f")
  fi
  # Generated by expo-module-scripts and now unresolvable; ESLint config lives
  # in the root .eslintrc.js and cascades down.
  f="packages/expo-pico-$p/.eslintrc.js"
  if [[ -e "$f" ]] && grep -q 'expo-module-scripts' "$f" 2>/dev/null; then
    targets+=("$f")
  fi
done

f=packages/expo-pico-core/src/ExpoPicoModule.ts
# NOTE: core's is NOT dead — it was rewritten as the Nitro-backed facade.
[[ -e "$f" ]] && echo "keeping (rewritten as facade): $f"

f=packages/expo-pico-core/expo-module.config.json
[[ -e "$f" ]] && targets+=("$f")

# Shared helpers with no remaining callers.
for f in \
  packages/internal/pico-platform-service-common/src/module-resolver.ts \
  packages/internal/pico-platform-service-common/src/pagination.ts \
  packages/internal/pico-platform-service-common/src/__tests__/module-resolver.test.ts
do
  [[ -e "$f" ]] && targets+=("$f")
done

# ── Optional: superseded by the example redesign ─────────────────────────────
# The home screen replaced the tab shell, and InteractiveCubeScene replaced the
# glTF scene root. Removing PicoSceneRoot also retires the BrainStem demo, which
# makes example/scripts/download-demo-model.js and its postinstall step dead —
# so this group is opt-in via --with-example.
if [[ "${2:-}" == "--with-example" || "${1:-}" == "--with-example" ]]; then
  for f in \
    example/src/ui/Tabs.tsx \
    example/src/scene/PicoSceneRoot.tsx \
    example/src/scene/GltfModel.tsx
  do
    [[ -e "$f" ]] && targets+=("$f")
  done
fi

if [[ ${#targets[@]} -eq 0 ]]; then
  echo "Nothing to remove."
  exit 0
fi

printf '%s\n' "${targets[@]}"
echo
echo "${#targets[@]} file(s)"

if [[ $APPLY -eq 1 ]]; then
  git rm -q -f --ignore-unmatch -- "${targets[@]}"
  echo "Removed. Review with: git status"
else
  echo "Dry run. Re-run with --apply to delete."
fi
