//
// ExpoPicoLeaderboards.cpp
//
// CMake needs one source file of its own to create the library target
// before `ExpoPicoLeaderboards+autolinking.cmake` appends the generated sources to it.
// Everything that does real work is either generated by nitrogen or
// written in Kotlin under `src/nitro`; this file only anchors the target,
// so it must stay in the build even though it exports nothing.
//

namespace expopico {

// Never called. Present so the translation unit is not empty, which some
// NDK toolchains warn about under -Wall.
void expopicoleaderboards_anchor() noexcept {}

} // namespace expopico
